export const AXES = [
  {
    id: "windows",
    name: "Windows Systems",
    subtitle: "incl. AD",
    questions: [
      { id: "win_q1", tag: "S", text: "Familiarity with building stable, reproducible Windows lab hosts for scenarios (setup + reset-ready)." },
      { id: "win_q2", tag: "S", text: "Familiarity with AD lab construction (domain setup, OUs, users/groups/service accounts) to match scenario needs." },
      { id: "win_q3", tag: "S", text: "Ability to configure permissions/access paths (shares, local rights, group membership, service permissions) to support scenario logic." },
      { id: "win_q4", tag: "S", text: "Familiarity with Windows policy configuration (baseline settings / GPO concepts) to enforce scenario conditions reliably." },
      { id: "win_q5", tag: "SOC", text: "Familiarity with Windows investigation telemetry (what sources exist and what each is useful for in an incident)." },
      { id: "win_q6", tag: "SOC", text: "Ability to interpret authentication/account activity in Windows/AD (normal vs suspicious behavior patterns)." },
      { id: "win_q7", tag: "SOC", text: "Ability to do Windows incident triage and containment (what to check first; safe actions like isolate/disable/reset)." },
      { id: "win_q8", tag: "PT", text: "Depth of understanding of Windows/AD authentication mechanics (why credential attacks work conceptually)." },
      { id: "win_q9", tag: "PT", text: "Depth of understanding of privilege boundaries and escalation surfaces in Windows environments (common misconfigs/abuse paths)." },
      { id: "win_q10", tag: "PT", text: "Depth of understanding of AD attack paths and defensive features (trust/delegation concepts, tiering/admin separation, certificate/PKI concepts)." },
    ],
  },
  {
    id: "linux",
    name: "Linux Systems",
    subtitle: "admin + hardening",
    questions: [
      { id: "lin_q1", tag: "S", text: "Ability to build reproducible Linux hosts for scenarios (services installed, configs, reset-ready state)." },
      { id: "lin_q2", tag: "S", text: "Familiarity with Linux users/permissions for scenario design (service accounts, sudo rules, file permissions)." },
      { id: "lin_q3", tag: "S", text: "Ability to configure Linux services needed by scenarios (web, db, agents, schedulers) predictably." },
      { id: "lin_q4", tag: "S", text: "Ability to prepare Linux-based scenario artifacts (data, logs, configs) so tasks behave consistently." },
      { id: "lin_q5", tag: "SOC", text: "Familiarity with Linux telemetry/log sources for investigations (what exists, what it indicates)." },
      { id: "lin_q6", tag: "SOC", text: "Ability to reason about Linux access and execution (logins, sudo usage, suspicious processes/persistence patterns)." },
      { id: "lin_q7", tag: "SOC", text: "Ability to perform Linux triage/containment safely (what to collect, what to change, what to isolate)." },
      { id: "lin_q8", tag: "PT", text: "Depth of understanding of Linux privilege escalation concepts (why misconfigs lead to root, common categories)." },
      { id: "lin_q9", tag: "PT", text: "Depth of understanding of Linux hardening and attack surface (what settings matter, typical gaps attackers use)." },
      { id: "lin_q10", tag: "PT", text: "Depth of understanding of Linux lateral movement/exfil paths (SSH keys, creds, service exposure concepts)." },
    ],
  },
  {
    id: "network",
    name: "Networking",
    subtitle: "arch / mgmt / security",
    questions: [
      { id: "net_q1", tag: "S", text: "Ability to design scenario network topology (segments, routing/NAT concepts, controlled connectivity) that supports the story." },
      { id: "net_q2", tag: "S", text: "Familiarity with core network services used in scenarios (DNS/DHCP/time sync concepts and why they matter)." },
      { id: "net_q3", tag: "S", text: "Ability to implement segmentation and access rules (firewall policy intent, allowed flows) for scenario objectives." },
      { id: "net_q4", tag: "S", text: "Ability to prepare network artifacts for scenarios (diagrams, intended flows, documented access paths)." },
      { id: "net_q5", tag: "SOC", text: "Familiarity with network security data sources (flow, firewall, proxy, DNS logs—conceptually)." },
      { id: "net_q6", tag: "SOC", text: "Ability to recognize common suspicious network patterns at a conceptual level (scanning, brute force, beaconing, exfil indicators)." },
      { id: "net_q7", tag: "SOC", text: "Ability to support incident work via network reasoning (scope, affected segments, containment options like blocking/isolation)." },
      { id: "net_q8", tag: "PT", text: "Depth of understanding of network attack paths (pivoting, segmentation-bypass categories, trust assumptions)." },
      { id: "net_q9", tag: "PT", text: "Depth of understanding of typical network misconfig risks (over-permissive rules, exposed management, weak remote access patterns)." },
      { id: "net_q10", tag: "PT", text: "Depth of understanding of secure network design principles (least privilege connectivity, defense-in-depth, monitoring placement concepts)." },
    ],
  },
  {
    id: "apps",
    name: "Applications",
    subtitle: "web/mobile/dev/reverse",
    questions: [
      { id: "app_q1", tag: "S", text: "Ability to deploy/configure application stacks for scenarios (web/API/db dependencies) in a stable, repeatable way." },
      { id: "app_q2", tag: "S", text: "Ability to implement scenario-relevant auth/session configuration (accounts/roles/tokens) so tasks are consistent." },
      { id: "app_q3", tag: "S", text: "Ability to prepare application artifacts and data for scenarios (seed data, logs, configs, predictable states)." },
      { id: "app_q4", tag: "S", text: "Ability to build/adapt intentionally vulnerable app conditions safely for training (controlled scope, no chaos)." },
      { id: "app_q5", tag: "SOC", text: "Familiarity with application investigation signals (app logs, auth logs, API access logs—what they reveal)." },
      { id: "app_q6", tag: "SOC", text: "Ability to reason about auth/session abuse in incidents (token misuse patterns, suspicious access behavior concepts)." },
      { id: "app_q7", tag: "SOC", text: "Ability to support IR with app-level containment thinking (rotate secrets, disable endpoints, reduce exposure conceptually)." },
      { id: "app_q8", tag: "PT", text: "Depth of understanding of common web/API vulnerability classes (categories and why they happen; not tool steps)." },
      { id: "app_q9", tag: "PT", text: "Depth of understanding of secure application design basics (authz boundaries, secrets handling, logging principles)." },
      { id: "app_q10", tag: "PT", text: "Mobile/reverse security concepts when needed (where secrets end up, common abuse categories, high-level reasoning)." },
    ],
  },
  {
    id: "automation",
    name: "Automation Tools",
    subtitle: "programming + IaC",
    questions: [
      { id: "aut_q1", tag: "S", text: "Ability to automate scenario deployment/config (repeatable setup, idempotent approach, fewer manual steps)." },
      { id: "aut_q2", tag: "S", text: "Familiarity with configuration management concepts/tools (Ansible-like thinking) for consistent lab state." },
      { id: "aut_q3", tag: "S", text: "Familiarity with infrastructure-as-code concepts/tools (Terraform-like thinking) for reproducible environments." },
      { id: "aut_q4", tag: "S", text: "Ability to manage versioning and rollback of automation/config changes (controlled releases, stability mindset)." },
      { id: "aut_q5", tag: "SOC", text: "Ability to automate evidence collection/normalization for investigations (repeatable triage data gathering)." },
      { id: "aut_q6", tag: "SOC", text: "Ability to integrate automation into workflows (alerts/enrichment/tickets) with reliability and safety." },
      { id: "aut_q7", tag: "SOC", text: "Maturity in handling secrets safely in automation (no hardcoding, access control, rotation mindset)." },
      { id: "aut_q8", tag: "PT", text: "Ability to automate verification/reproduction of findings responsibly (controlled scripts, clear evidence)." },
      { id: "aut_q9", tag: "PT", text: "Understanding of how automation introduces risk (over-privileged tokens, supply chain, unsafe defaults) and mitigation." },
      { id: "aut_q10", tag: "PT", text: "Overall engineering quality of scripts/tools (readability, error handling, docs, maintainability)." },
    ],
  },
  {
    id: "leader",
    name: "Leader",
    subtitle: "teamwork + comms + English",
    questions: [
      { id: "lead_q1", tag: "TEAM", text: "Ownership: takes tasks end-to-end; closes loops; does not disappear after handoff." },
      { id: "lead_q2", tag: "TEAM", text: "Works predictably in a team process (planning, updates, delivery discipline)." },
      { id: "lead_q3", tag: "TEAM", text: "Collaborates across functions (scenarios/infra/SOC/PT) without friction." },
      { id: "lead_q4", tag: "TEAM", text: "Initiative: proposes improvements, identifies risks early, acts without being pushed." },
      { id: "lead_q5", tag: "TEAM", text: "Mentoring/helpfulness: supports teammates, reviews, shares knowledge." },
      { id: "lead_q6", tag: "TEAM", text: "Professional under stress: prioritization, calm comms, consistency." },
      { id: "lead_q7", tag: "COMMS", text: "Written clarity: tickets, docs, runbooks, scenario notes are understandable." },
      { id: "lead_q8", tag: "COMMS", text: "Verbal clarity: explains decisions and status in meetings/hand-offs." },
      { id: "lead_q9", tag: "EN", text: "English reading: can consume vendor docs/advisories/guides without constant translation." },
      { id: "lead_q10", tag: "EN", text: "English writing/speaking: can write reports/messages and participate in calls at a work-usable level." },
    ],
  },
];
